name: DBIPROP Change Detector
on:
  pull_request:
    branches: [main]
    types: [opened]


jobs:
  dbiprop-updater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm install
      - name: Check if Prisma schema changed
        id: changed-files
        uses: tj-actions/changed-files@v45
      - name: List all changed files
      # git diff --name-only ${github.event.before} ${github.event.after} > /tmp/diff.txt
      # cat /tmp/diff.txt >> /tmp/event.txt
      # dict_values=$(awk '/"dict":/ {sub(/"/, "", $2); print $2}' "$file")
      # echo "Values of 'dict' attribute for each new attribute: $dict_values" >> /tmp/event.txt
      # if [ "$(basename "$file" | cut -d. -f2-)" == "json" ]; then
      #   value=$(awk -F'"' '/"file":/{print $4}' "$file")
      #   echo "FILE NAME: $value" >> /tmp/event.txt
      # fi
      # git diff --name-only $GITHUB_BASE_REF..origin/$GITHUB_HEAD_REF > /tmp/diff.txt
      # echo "Added content in $file:"
      # git diff -U0 $GITHUB_BASE_REF..$GITHUB_SHA -- $file >> /tmp/event.txt
        run: |
          git fetch origin
          echo "TICKET: ${GITHUB_HEAD_REF}" >> /tmp/event.txt
          echo "CHANGED FILES:" >> /tmp/event.txt
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed" >> /tmp/event.txt
            if [ "$(basename "$file" | cut -d. -f2-)" == "json" ]; then
              echo "Added content in $file:" >> /tmp/event.txt
              cat $file >> /tmp/added-content.txt
            fi
          done
      - name: Upload changed files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed-files
          path: /tmp/event.txt
      # - name: Upload added content as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: added-content
      #     path: /tmp/added-content.txt
