name: DBIPROP Change Detector
on:
  push:
    branches:
      - main
    types:
      - forced
    pull_request:
      branches:
        - main'
      types:
        - merged


jobs:
  dbiprop-updater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm install
      - name: Get changed files
# jq '.pull_request.changed_files[] |.filename' /tmp/event.json > /tmp/changed_files.txt
# jq '.pull_request.merged_files[] |.filename' /tmp/event.json > /tmp/changed_files.txt
        run: |
          echo "${GITHUB_EVENT_PATH}" > /tmp/event.json
          jq '.pull_request.files[] |.filename' /tmp/event.json > /tmp/changed_files.txt
      - name: Upload changed files as artifact
          uses: actions/upload-artifact@v3
          with:
            name: changed-files
            path: /tmp/changed_files.txt
