name: DBIPROP Change Detector
on:
  pull_request:
    branches: [main]
    types: [opened]


jobs:
  dbiprop-updater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Node.js setup
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm install
      - name: Check if Prisma schema changed
        id: changed-files
        uses: tj-actions/changed-files@v45
      - name: List all changed files
        run: |
          echo "TICKET: ${GITHUB_HEAD_REF}" >> /tmp/event.txt
          echo "CHANGED FILES:" >> /tmp/event.txt
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [ "$(basename "$file" | cut -d. -f2-)" == "json" ]; then
              value=$(awk -F'"' '/"file":/{print $4}' "$file")
              echo "$file is a JSON file and was changed. The value of 'file' is: $value" >> /tmp/event.txt
              new_attributes=$(awk -v RS=',\s*' '/"attributes":/ {flag=1} flag==1 && /"/ {print $1}' "$file" | sed 's/"//g')
              echo "New attributes added to $file: $new_attributes" >> /tmp/event.txt
            else
              echo "$file was changed" >> /tmp/event.txt
            fi
          done
      - name: Upload changed files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed-files
          path: /tmp/event.txt
